kind: pipeline
type: docker
name: cypress-tests

steps:
  - name: install dependencies
    image: cypress/browsers:node-18.12.0-chrome-106
    commands:
      - npm ci

  - name: run cypress tests
    image: cypress/browsers:node-18.12.0-chrome-106
    commands:
      - npm run cy:run