kind: pipeline
type: docker
name: cypress-tests

steps:
  - name: install dependencies
    image: cypress/included:latest
    commands:
      - npm ci

  - name: run cypress tests
    image: cypress/included:latest
    commands:
      - npm run cy:run