kind: pipeline
type: docker
name: cypress-tests

matrix:
  include:
    - PART: 0
      PART_TOTAL: 2
    - PART: 1
      PART_TOTAL: 2

steps:
  - name: run cypress
    image: cypress/included:13.6.6
    environment:
      PART: ${PART}
      PART_TOTAL: ${PART_TOTAL}
    commands:
      - echo "Executando parte $PART de $PART_TOTAL"
      - npm ci
      - npx cypress-split --ci-build-id $DRONE_BUILD_NUMBER --split $PART --total $PART_TOTAL run
