kind: pipeline
name: cypress-runner-1

node: 
  node: runner-1

steps:
  - name: run-cypress-part-1
    image: cypress/included:latest
    environment:
      SPLIT: 2
      SPLIT_INDEX: 0
    commands:
      - npm ci
      - npm run cy:run

---

kind: pipeline
name: cypress-runner-2

node: 
  node: runner-2

steps:
  - name: run-cypress-part-2
    image: cypress/included:latest
    environment:
      SPLIT: 2
      SPLIT_INDEX: 1
    commands:
      - npm ci
      - npm run cy:run