kind: pipeline
type: docker
name: cypress-tests

matrix:
  include:
    - SPLIT: 0
      SPLIT_TOTAL: 2
    - SPLIT: 1
      SPLIT_TOTAL: 2

steps:
  - name: run cypress tests
    image: cypress/included:latest
    environment:
      SPLIT:
        from_secret: SPLIT
      SPLIT_TOTAL:
        from_secret: SPLIT_TOTAL
    commands:
      - echo "Executando SPLIT={$SPLIT} de ${SPLIT_TOTAL}"
      - npm ci
      - npm run cy:run