name: End-to-end tests
on: push
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6