name: End-to-end tests

on: push

jobs:
  run-automation:
    runs-on: self-hosted
    strategy:
      matrix:
        shardIndex: [0, 1]
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm ci
      - name: Rodar testes Cypress em paralelo
        uses: cypress-io/github-action@v6
        with:
          install: false
          runTests: true
        env:
          SPLIT: 2
          SPLIT_INDEX: ${{ matrix.shardIndex }} 